{% macro endpoint_registry(database, schema) %}

{% set sql %}
    MERGE INTO {{ database }}.{{ schema }}.VIVENU_STREAM_CONFIG T
    USING (
        SELECT
            F.VALUE:name::VARCHAR AS STREAM_NAME,
            COALESCE(F.VALUE:enabled::BOOLEAN, FALSE) AS ENABLED,
            COALESCE(
                F.VALUE:lookback::NUMBER,
                IFF(F.VALUE:mode::VARCHAR = 'SNAPSHOT', 0, 600)
            ) AS LOOKBACK_SECONDS,
            COALESCE(
                F.VALUE:reconcile::NUMBER,
                IFF(F.VALUE:mode::VARCHAR = 'SNAPSHOT', 0, 168)
            ) AS RECONCILE_HOURS,
            COALESCE(
                F.VALUE:every::NUMBER,
                IFF(F.VALUE:mode::VARCHAR = 'SNAPSHOT', 1440, 0)
            ) AS MIN_SYNC_INTERVAL_MINUTES,
            F.VALUE AS API_SPEC
        FROM TABLE(
            FLATTEN(INPUT => PARSE_JSON($$
    [
      {
        "name":"events",
        "enabled":true,
        "path":"/events",
        "mode":"UPDATED",
        "cursor":"updatedAt",
        "shape":"rows"
      },
      {
        "name":"customers",
        "enabled":true,
        "path":"/customers/rich",
        "mode":"UPDATED",
        "cursor":"updatedAt"
      },
      {
        "name":"transactions",
        "enabled":true,
        "path":"/transactions",
        "mode":"UPDATED",
        "cursor":"updatedAt"
      },
      {
        "name":"tickets",
        "enabled":true,
        "path":"/tickets",
        "mode":"UPDATED",
        "cursor":"updatedAt",
        "shape":"rows"
      },
      {
        "name":"subscriptions",
        "enabled":true,
        "path":"/subscriptions",
        "mode":"UPDATED",
        "cursor":"updatedAt",
        "require_cursor":false
      },
      {
        "name":"scans",
        "service":"scans",
        "path":"/scans",
        "mode":"EVENT_TIME",
        "cursor":"time",
        "lookback":600
      },

      {
        "name":"checkouts",
        "enabled":true,
        "path":"/checkouts",
        "mode":"UPDATED",
        "cursor":"updatedAt",
        "redact":[
          "secret",
          "seatingReservationToken",
          "items.*.seatingReservationToken"
        ]
      },
      {
        "name":"ticket_transfers",
        "path":"/ticket-transfers",
        "mode":"UPDATED",
        "cursor":"updatedAt"
      },
      {
        "name":"invoices",
        "enabled":true,
        "path":"/invoices",
        "mode":"CREATED",
        "cursor":"createdAt",
        "shape":"rows",
        "lookback":600,
        "reconcile":24,
        "redact":["secret"]
      },
      {
        "name":"payment_requests",
        "enabled":true,
        "path":"/payments/requests",
        "mode":"CREATED",
        "cursor":"createdAt",
        "lookback":600,
        "reconcile":24,
        "redact":["secret","processors.*.data","history.*.data"]
      },
      {
        "name":"purchase_intents",
        "enabled":true,
        "path":"/purchaseintents",
        "mode":"CREATED",
        "cursor":"createdAt",
        "from_param":"createdAtStart",
        "to_param":"createdAtEnd",
        "allow_upper_boundary":true,
        "shape":"rows",
        "lookback":600,
        "reconcile":24,
        "redact":["secret","seatingReservationToken"]
      },

      {
        "name":"coupons",
        "path":"/coupon/rich",
        "mode":"SNAPSHOT",
        "shape":"rows",
        "every":360
      },
      {
        "name":"coupon_series",
        "path":"/coupon/series",
        "mode":"SNAPSHOT"
      },
      {
        "name":"vouchers",
        "path":"/vouchers",
        "mode":"SNAPSHOT",
        "keys":["code"],
        "every":360
      },
      {
        "name":"products",
        "path":"/products/rich",
        "mode":"SNAPSHOT"
      },
      {
        "name":"product_streams",
        "path":"/products/streams/rich",
        "mode":"SNAPSHOT"
      },
      {
        "name":"product_stream_products",
        "path":"/products/streams/{id}/products",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none",
        "parent":{
          "stream":"product_streams",
          "fields":{"id":"_id"}
        }
      },
      {
        "name":"price_tables",
        "enabled":true,
        "path":"/price-tables",
        "mode":"SNAPSHOT"
      },
      {
        "name":"data_fields",
        "enabled":true,
        "path":"/data-fields",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none"
      },
      {
        "name":"sales_channels",
        "enabled":true,
        "path":"/sales-channels",
        "mode":"SNAPSHOT"
      },
      {
        "name":"sales_channel_groups",
        "enabled":true,
        "path":"/sales-channels/groups",
        "mode":"SNAPSHOT"
      },

      {
        "name":"pos_devices",
        "path":"/pos",
        "mode":"SNAPSHOT",
        "shape":"array",
        "redact":["restrictions.code"]
      },
      {
        "name":"pos_sessions",
        "path":"/pos/{id}/sessions",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none",
        "every":360,
        "parent":{
          "stream":"pos_devices",
          "fields":{"id":"_id"}
        }
      },
      {
        "name":"pos_journal_logs",
        "path":"/pos/{id}/logs",
        "mode":"SNAPSHOT",
        "shape":"rows",
        "every":360,
        "parent":{
          "stream":"pos_devices",
          "fields":{"id":"_id"}
        }
      },
      {
        "name":"webhooks",
        "path":"/webhooks",
        "mode":"SNAPSHOT",
        "redact":["hmacKey"]
      },

      {
        "name":"fundraise_campaigns",
        "path":"/fundraise/campaigns",
        "mode":"SNAPSHOT"
      },
      {
        "name":"fundraise_funds",
        "path":"/fundraise/funds",
        "mode":"SNAPSHOT"
      },
      {
        "name":"fundraise_donations",
        "path":"/fundraise/donations/{id}",
        "mode":"SNAPSHOT",
        "shape":"object",
        "paging":"none",
        "lookup":true
      },
      {
        "name":"fundraise_pledges",
        "path":"/fundraise/pledges/{id}",
        "mode":"SNAPSHOT",
        "shape":"object",
        "paging":"none",
        "lookup":true
      },
      {
        "name":"purchase_intent_strategies",
        "path":"/purchaseintents/strategies/{id}",
        "mode":"SNAPSHOT",
        "shape":"object",
        "paging":"none",
        "keys":[],
        "lookup":true
      },

      {
        "name":"payment_gateways",
        "path":"/payments/gateways",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none",
        "redact":["secret","data"]
      },
      {
        "name":"customer_payment_methods",
        "enabled":true,
        "path":"/customers/{id}/payment-methods",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none",
        "parent":{
          "stream":"customers",
          "fields":{"id":"_id"}
        },
        "redact":["secret","token","data","paymentDetails"]
      },

      {
        "name":"access_users",
        "path":"/accessusers",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none",
        "redact":["token"]
      },
      {
        "name":"access_lists",
        "path":"/access-lists",
        "mode":"SNAPSHOT",
        "redact":["http.hmacKey"]
      },
      {
        "name":"access_list_entries",
        "path":"/access-lists/{listId}/entries",
        "mode":"SNAPSHOT",
        "every":360,
        "parent":{
          "stream":"access_lists",
          "fields":{"listId":"_id"}
        }
      },
      {
        "name":"scan_groups",
        "path":"/scan-groups",
        "mode":"SNAPSHOT"
      },

      {
        "name":"seating_events",
        "service":"seating",
        "path":"/event",
        "mode":"SNAPSHOT",
        "shape":"array",
        "paging":"none"
      },
      {
        "name":"seating_contingents",
        "service":"seating",
        "path":"/event/{id}/contingents",
        "mode":"SNAPSHOT",
        "shape":"document",
        "paging":"none",
        "every":360,
        "parent":{
          "stream":"seating_events",
          "fields":{"id":"_id"}
        }
      },
      {
        "name":"seatmap_revisions",
        "service":"seating",
        "path":"/seatmap/{mapId}/revision",
        "mode":"SNAPSHOT",
        "shape":"document",
        "paging":"none",
        "parent":{
          "stream":"seating_events",
          "fields":{"mapId":"seatMapId"}
        }
      },
      {
        "name":"seatmap_revision_details",
        "service":"seating",
        "path":"/seatmap/{mapId}/revision/{revisionId}",
        "mode":"SNAPSHOT",
        "shape":"document",
        "paging":"none",
        "params":{"includeSeatmap":true},
        "parent":{
          "stream":"seating_events",
          "fields":{
            "mapId":"seatMapId",
            "revisionId":"revisionId"
          }
        }
      },
      {
        "name":"seating_object_status",
        "service":"seating",
        "path":"/event/{id}/status/{objectId}",
        "mode":"SNAPSHOT",
        "shape":"object",
        "paging":"none",
        "keys":[],
        "lookup":true,
        "every":60
      },
      {
        "name":"seating_object_logs",
        "service":"seating",
        "path":"/event/{id}/status/{objectId}/logs",
        "mode":"SNAPSHOT",
        "shape":"document",
        "paging":"none",
        "lookup":true,
        "every":360
      },

      {
        "name":"dynamic_prices",
        "service":"pricing",
        "path":"/pricing/prices",
        "mode":"SNAPSHOT",
        "every":60
      }
    ]
    $$))
        ) F
    ) S
    ON T.STREAM_NAME = S.STREAM_NAME
    WHEN NOT MATCHED THEN INSERT (
        STREAM_NAME,
        ENABLED,
        LOOKBACK_SECONDS,
        RECONCILE_HOURS,
        MIN_SYNC_INTERVAL_MINUTES,
        API_SPEC
    ) VALUES (
        S.STREAM_NAME,
        S.ENABLED,
        S.LOOKBACK_SECONDS,
        S.RECONCILE_HOURS,
        S.MIN_SYNC_INTERVAL_MINUTES,
        S.API_SPEC
    );
{% endset %}

{% do run_query(sql) %}
{% do log("Endpoint registry populated in " ~ database ~ "." ~ schema, info=True) %}

{% endmacro %}