{% macro create_operational_table_view(database, schema) %}

{% set sql %}
    USE ROLE VIVENU_INGEST_ROLE;
    USE WAREHOUSE VIVENU_INGEST_WH;
    ALTER SESSION SET AUTOCOMMIT = TRUE;
    ALTER SESSION SET TIMEZONE = 'UTC';

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_CONFIG (
        CONFIG_ID NUMBER NOT NULL,
        INITIAL_FROM_TS TIMESTAMP_TZ NOT NULL,
        PAGE_SIZE NUMBER NOT NULL,
        REQUEST_TIMEOUT_SECONDS NUMBER NOT NULL,
        REQUEST_DELAY_MS NUMBER NOT NULL,
        MAX_PAGES_PER_STREAM NUMBER NOT NULL,
        SAFETY_LAG_SECONDS NUMBER NOT NULL,
        CONSTRAINT VIVENU_CONFIG_PK PRIMARY KEY (CONFIG_ID)
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_STREAM_CONFIG (
        STREAM_NAME VARCHAR NOT NULL,
        ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
        LOOKBACK_SECONDS NUMBER NOT NULL,
        RECONCILE_HOURS NUMBER NOT NULL,
        MIN_SYNC_INTERVAL_MINUTES NUMBER NOT NULL DEFAULT 0,
        API_SPEC VARIANT NOT NULL,
        CONSTRAINT VIVENU_STREAM_CONFIG_PK PRIMARY KEY (STREAM_NAME)
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_SYNC_CONTROL (
        STREAM_NAME VARCHAR NOT NULL,
        LAST_SUCCESS_TO_TS TIMESTAMP_TZ,
        LAST_SUCCESS_AT TIMESTAMP_TZ,
        LAST_FULL_SYNC_AT TIMESTAMP_TZ,
        LAST_RUN_ID VARCHAR,
        CONSTRAINT VIVENU_SYNC_CONTROL_PK PRIMARY KEY (STREAM_NAME)
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_SYNC_RUNS (
        RUN_ID VARCHAR NOT NULL,
        STARTED_AT TIMESTAMP_TZ NOT NULL,
        FINISHED_AT TIMESTAMP_TZ,
        STATUS VARCHAR NOT NULL,
        REQUESTED_STREAM VARCHAR,
        IS_AUTOMATIC BOOLEAN NOT NULL,
        FORCE_FULL BOOLEAN NOT NULL,
        REPLAY_FROM_TS TIMESTAMP_TZ,
        REPLAY_TO_TS TIMESTAMP_TZ,
        API_REQUESTS NUMBER,
        RECORDS_FETCHED NUMBER,
        STREAM_RESULTS VARIANT,
        ERROR_MESSAGE VARCHAR,
        CONSTRAINT VIVENU_SYNC_RUNS_PK PRIMARY KEY (RUN_ID)
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_SYNC_LOCK (
        LOCK_ID NUMBER NOT NULL,
        RUN_ID VARCHAR,
        ACQUIRED_AT TIMESTAMP_TZ,
        CONSTRAINT VIVENU_SYNC_LOCK_PK PRIMARY KEY (LOCK_ID)
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_LOOKUP_CONTEXTS (
        STREAM_NAME VARCHAR NOT NULL,
        CONTEXT VARIANT NOT NULL,
        ENABLED BOOLEAN NOT NULL DEFAULT TRUE
    );

    CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_RAW_CURRENT (
        STREAM_NAME VARCHAR NOT NULL,
        RECORD_ID VARCHAR NOT NULL,
        SOURCE_UPDATED_AT TIMESTAMP_TZ,
        DATA VARIANT NOT NULL,
        SOURCE_CONTEXT VARIANT,
        RECORD_HASH VARCHAR NOT NULL,
        FIRST_LOADED_AT TIMESTAMP_TZ NOT NULL,
        LAST_CHANGED_AT TIMESTAMP_TZ NOT NULL,
        LAST_RUN_ID VARCHAR NOT NULL,
        CONSTRAINT VIVENU_RAW_CURRENT_PK PRIMARY KEY (STREAM_NAME, RECORD_ID)
    );

    CREATE TRANSIENT TABLE IF NOT EXISTS {{ database }}.{{ schema }}.VIVENU_LOAD_STAGE (
        RUN_ID VARCHAR NOT NULL,
        STREAM_NAME VARCHAR NOT NULL,
        RECORD_ID VARCHAR NOT NULL,
        SOURCE_UPDATED_AT TIMESTAMP_TZ,
        PAYLOAD_JSON VARCHAR NOT NULL,
        FETCH_SEQUENCE NUMBER NOT NULL,
        SOURCE_CONTEXT_JSON VARCHAR NOT NULL
    );
{% endset %}

{% do run_query(sql) %}
{% do log("Operational tables created successfully in " ~ database ~ "." ~ schema, info=True) %}

{% endmacro %}