-- =====================================================================
-- 1. ADMINISTRATIVE INFRASTRUCTURE
-- =====================================================================

USE ROLE ACCOUNTADMIN;

ALTER SESSION SET AUTOCOMMIT = TRUE;
ALTER SESSION SET TIMEZONE = 'UTC';

CREATE DATABASE IF NOT EXISTS VIVENU_API_DATA;

CREATE SCHEMA IF NOT EXISTS VIVENU_API_DATA.VIVENU_NATIVE;

CREATE WAREHOUSE IF NOT EXISTS VIVENU_INGEST_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE NETWORK RULE
    VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = (
        'vivenu.com',
        'portier.vivenu.com',
        'seatmap.vivenu.com',
        'marketmaker.vivenu.com'
    );

-- Replace this placeholder before installation.
-- IF NOT EXISTS preserves an existing credential on a later rerun.
-- Use ALTER SECRET for an intentional credential rotation.
CREATE SECRET IF NOT EXISTS
    VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_KEY
    TYPE = GENERIC_STRING
    SECRET_STRING = 'KEY';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION VIVENU_API_ACCESS
    ALLOWED_NETWORK_RULES = (
        VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_RULE
    )
    ALLOWED_AUTHENTICATION_SECRETS = (
        VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_KEY
    )
    ENABLED = TRUE;

CREATE ROLE IF NOT EXISTS VIVENU_INGEST_ROLE;

GRANT ROLE VIVENU_INGEST_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE VIVENU_API_DATA
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON SCHEMA VIVENU_API_DATA.VIVENU_NATIVE
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON SCHEMA VIVENU_API_DATA.VIVENU_BRONZE
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON SCHEMA VIVENU_API_DATA.VIVENU_SILVER
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON SCHEMA VIVENU_API_DATA.GITHUB_DEPLOYMENT
    TO ROLE VIVENU_INGEST_ROLE;

GRANT CREATE STAGE ON SCHEMA VIVENU_API_DATA.VIVENU_BRONZE TO ROLE VIVENU_INGEST_ROLE;
GRANT CREATE STAGE ON SCHEMA VIVENU_API_DATA.GITHUB_DEPLOYMENT TO ROLE VIVENU_INGEST_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TASK
    ON SCHEMA VIVENU_API_DATA.VIVENU_NATIVE
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON WAREHOUSE VIVENU_INGEST_WH
    TO ROLE VIVENU_INGEST_ROLE;

GRANT USAGE ON INTEGRATION VIVENU_API_ACCESS
    TO ROLE VIVENU_INGEST_ROLE;

GRANT READ ON SECRET
    VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_KEY
    TO ROLE VIVENU_INGEST_ROLE;

GRANT READ ON SECRET
    VIVENU_API_DATA.VIVENU_NATIVE.VIVENU_API_KEY
    TO ROLE VIVENU_INGEST_ROLE;

GRANT EXECUTE TASK ON ACCOUNT
    TO ROLE VIVENU_INGEST_ROLE;


GRANT CREATE SECRET
    ON SCHEMA VIVENU_API_DATA.VIVENU_BRONZE
    TO ROLE VIVENU_INGEST_ROLE;

GRANT CREATE SECRET
    ON SCHEMA VIVENU_API_DATA.GITHUB_DEPLOYMENT
    TO ROLE VIVENU_INGEST_ROLE;

GRANT CREATE API INTEGRATION
ON ACCOUNT
TO ROLE VIVENU_INGEST_ROLE;

GRANT CREATE GIT REPOSITORY
ON SCHEMA VIVENU_API_DATA.GITHUB_DEPLOYMENT
TO ROLE VIVENU_INGEST_ROLE;


USE ROLE VIVENU_INGEST_ROLE;
USE DATABASE VIVENU_API_DATA;
USE SCHEMA VIVENU_NATIVE;
USE WAREHOUSE VIVENU_INGEST_WH;

























USE ROLE ACCOUNTADMIN;

-- 1. Create Target Analytics Database and Schemas
CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.SILVER; -- Cleaned / Staging
CREATE SCHEMA IF NOT EXISTS ANALYTICS.GOLD;   -- Star Schema / Marts

-- 2. Create dbt Execution Warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 3. Create dbt Service Role
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;

-- 4. Grant Database & Schema Permissions
GRANT USAGE ON DATABASE VIVENU_API_DATA TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA VIVENU_API_DATA.VIVENU_NATIVE TO ROLE DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA VIVENU_API_DATA.VIVENU_NATIVE TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA VIVENU_API_DATA.VIVENU_NATIVE TO ROLE DBT_ROLE;

GRANT ALL ON DATABASE ANALYTICS TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE DBT_ROLE;

GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;