/*
VIVENU TO BRAZE V2 - USES THE UPDATED VIEWS
Prerequisite: run Vivenu_Braze_View_Updates.sql first.
Source views: RAW_INGESTION.VIVENU_NATIVE.CUSTOMERS, TRANSACTIONS, TICKETS, EVENTS.
Build schema: BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.
Targets: the four existing BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_* tables.

Run sections 1-6 for installation and a validation build. Section 7 has commented
cutover commands. On first installation the new task is suspended. Re-running
this script does not suspend an already enabled task: suspend it before upgrades.
No changes to source views, old tasks or existing Braze targets during validation.

CONFIRMED RULES
- Vivenu contains new purchases. Keep historical Ticketek target rows.
- Netball WA treats purchase as marketing consent. Eligible profile payloads set
  email_subscribe='subscribed' without requiring MARKETING_CONSENT=true.
- Preserve legacy age rules through configuration: match profile groups have no
  age threshold; member profile and membership event groups require age 18.
  NULL DOB does not meet an age threshold. Global email_subscribe remains subscribed.
- Preserve legacy email identity SHA2(TRIM(email),256), including source case.
- Preserve the four output contracts and event names. Prefix new order IDs vivenu:.

CONFIGURATION
- No fixed event IDs or years. V_EVENT_MAP derives rows from EVENTS.
- Default rule: event names containing 'membership' classify as MEMBER; other
  named ticket events classify as MATCH. This is a naming convention inferred
  from the supplied membership examples, not a verified Vivenu type enumeration.
  Plan/MULTI evidence conflicting with default MATCH is held for review.
- One year in the event name supplies season. Match events without a year use
  START_AT's year. Memberships without a clear year require an override.
  An ambiguous multi-year name also requires an override.
- Member product prefix comes from CONTROL, package from the event name without
  its year. Round is extracted only from explicit 'round N' or 'rd N' text.
  Opposition and offer code are not guessed. Opposition can be overridden;
  offer_code is omitted until a source mapping is confirmed.
- EVENT_OVERRIDES is empty initially and used only for exceptions.
- SUBSCRIPTION_GROUP_CONFIG is seeded once from existing Braze group IDs.
  Environment, target, minimum age and enabled status are editable there.
  These destination IDs cannot be discovered from Vivenu. No IDs occur in payload SQL.
- Environment selects subscription configuration only. This file's publication
  targets are explicitly production; changing ENVIRONMENT does not redirect them.

PROCESSING
- Only COMPLETE / RECEIVED AUD orders qualify initially. Other statuses are
  reported in V_ISSUES, including cancellations and unpaid reservations.
- Source prices are used as dollars, consistent with supplied examples.
  Totals sum eligible ticket lines, excluding separate fees, as in the old process.
- Whole orders with partial cancellation detail are held pending net-quantity
  verification. No refund or unsubscribe is inferred from disappearing records.
- Membership orders require matching VALID tickets with member number/barcode
  and complete ticket counts. Incomplete orders are visible in V_ISSUES.
- Existing complimentary/stakeholder membership exclusions are retained.
- Profile-only customers without a qualifying purchase do not become candidates.
- Full recomputation detects customer/ticket/config changes; MERGE updates only
  changed payloads. No source watermark can hide related-record changes.
- UTC TIMESTAMP_NTZ UPDATED_AT, not CURRENT_DATE or a future-dated value.
- Changed published events remain held unless ALLOW_EVENT_REPLAY is enabled;
  a resent event may duplicate activity in Braze. No cancellation retracts history.
- Atomic four-table publication; validation outputs preserve their own history.
  V_CANDIDATES shows the current eligible set. Publication uses that current set.

Run with source SELECT, build-schema CREATE and warehouse access. Publication
also requires DML rights on the existing targets and UTC TIMESTAMP_NTZ timestamp
columns. The SQL has local parser/sample checks only, not Snowflake execution.
Live validation must include linked member tickets and a normal match purchase.
*/

-- 1. Isolated schema and explicit configuration.
CREATE SCHEMA IF NOT EXISTS BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2;
USE SCHEMA BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2;
USE WAREHOUSE WH_BRAZE_PRD;

CREATE TABLE IF NOT EXISTS CONTROL (
 CONFIG_ID NUMBER, ALLOW_PUBLISH BOOLEAN, ALLOW_EVENT_REPLAY BOOLEAN,
 ENVIRONMENT VARCHAR, MEMBER_EVENT_NAME_REGEX VARCHAR,
 DEFAULT_SALE_KIND VARCHAR, MEMBER_PRODUCT_PREFIX VARCHAR
);
INSERT INTO CONTROL
SELECT 1,FALSE,FALSE,'PRODUCTION','.*membership.*','MATCH','WCF Membership '
WHERE NOT EXISTS (SELECT 1 FROM CONTROL);

-- No event IDs or seasons are seeded. Overrides are optional exceptions.
CREATE TABLE IF NOT EXISTS EVENT_OVERRIDES (
 EVENT_ID VARCHAR, SALE_KIND VARCHAR, SEASON VARCHAR,
 PRODUCT_NAME VARCHAR, PACKAGE_NAME VARCHAR, OPPOSITION VARCHAR,
 ROUND_NAME VARCHAR, ENABLED BOOLEAN
);

-- Braze owns these IDs: seed the existing destinations once, then manage here.
-- Environment, applicability and age rules are configuration, not payload SQL.
CREATE TABLE IF NOT EXISTS SUBSCRIPTION_GROUP_CONFIG (
 ENVIRONMENT VARCHAR, TARGET_NAME VARCHAR, GROUP_ID VARCHAR,
 MIN_AGE NUMBER, ENABLED BOOLEAN
);
MERGE INTO SUBSCRIPTION_GROUP_CONFIG t USING (
 WITH groups AS (
  SELECT column1 AS GROUP_ID FROM VALUES
  ('69a15dd9-bf6a-49dd-8414-04dcc0b951a0'),
  ('eae8c034-cbb6-4b6c-ab76-01aa34a97d6c'),
  ('a487c114-51fb-47dd-966b-0add47491472'),
  ('e7cd6b08-a430-48c2-a8a6-24cd73d9e2e7'),
  ('57e895f8-d0bb-476d-8ceb-62541866d6e5'),
  ('40fefb6a-2ce9-4db1-a82a-e5766de3f6cf')
 ), scopes AS (
  SELECT column1 AS TARGET_NAME,column2::NUMBER AS MIN_AGE FROM VALUES
  ('TICKETEK_NWA_PROFILES',NULL),('TICKETEK_MEMBER_PROFILES',18)
 )
 SELECT 'PRODUCTION' AS ENVIRONMENT,s.TARGET_NAME,g.GROUP_ID,s.MIN_AGE
 FROM groups g CROSS JOIN scopes s
 UNION ALL
 SELECT 'PRODUCTION','TICKETEK_MEMBER_SALES',
 '49c1afa6-22fe-4994-a7c1-bf558214fe12',18
) s ON t.ENVIRONMENT=s.ENVIRONMENT AND t.TARGET_NAME=s.TARGET_NAME AND t.GROUP_ID=s.GROUP_ID
WHEN NOT MATCHED THEN INSERT VALUES(s.ENVIRONMENT,s.TARGET_NAME,s.GROUP_ID,s.MIN_AGE,TRUE);

-- Automatic classification is a visible business rule, not an API guarantee:
-- membership-named events -> MEMBER; other named ticket events -> configured
-- default MATCH. A line with a plan or MULTI ticket under a default-match event
-- is held for classification review, rather than silently sent as a match sale.
-- Change CONTROL.MEMBER_EVENT_NAME_REGEX or add an override for exceptions.
CREATE OR REPLACE VIEW V_EVENT_MAP AS
WITH inferred AS (
 SELECT e.*,
 CASE WHEN NULLIF(TRIM(e.EVENT_NAME),'') IS NULL THEN NULL
  WHEN REGEXP_LIKE(e.EVENT_NAME,c.MEMBER_EVENT_NAME_REGEX,'i') THEN 'MEMBER'
  ELSE c.DEFAULT_SALE_KIND END AS INFERRED_KIND,
 CASE WHEN REGEXP_COUNT(e.EVENT_NAME,'(19|20)[0-9]{2}')=1
  THEN REGEXP_SUBSTR(e.EVENT_NAME,'(19|20)[0-9]{2}') END AS NAME_SEASON,
 c.MEMBER_PRODUCT_PREFIX,
 CASE WHEN NULLIF(TRIM(e.EVENT_NAME),'') IS NULL THEN 'MISSING_NAME'
  WHEN REGEXP_LIKE(e.EVENT_NAME,c.MEMBER_EVENT_NAME_REGEX,'i') THEN 'MEMBERSHIP_NAME_RULE'
  ELSE 'DEFAULT_MATCH_RULE' END AS INFERRED_REASON
 FROM RAW_INGESTION.VIVENU_NATIVE.EVENTS e
 CROSS JOIN CONTROL c WHERE c.CONFIG_ID=1
), resolved AS (
 SELECT e.EVENT_ID,e.SELLER_ID,e.EVENT_NAME,e.START_AT AS EVENT_AT,
 COALESCE(o.SALE_KIND,e.INFERRED_KIND) AS SALE_KIND,
 COALESCE(o.SEASON,e.NAME_SEASON,
  IFF(COALESCE(o.SALE_KIND,e.INFERRED_KIND)='MATCH'
   AND REGEXP_COUNT(e.EVENT_NAME,'(19|20)[0-9]{2}')=0,
   TO_CHAR(e.START_AT,'YYYY'),NULL)) AS SEASON,
 o.PRODUCT_NAME AS OVERRIDE_PRODUCT_NAME,o.PACKAGE_NAME AS OVERRIDE_PACKAGE_NAME,
 e.MEMBER_PRODUCT_PREFIX,o.OPPOSITION,
 COALESCE(o.ROUND_NAME,REGEXP_SUBSTR(e.EVENT_NAME,
  '(round|rd)[[:space:]]*([0-9]+)',1,1,'ie',2)) AS ROUND_NAME,
 COALESCE(o.ENABLED,TRUE) AS ENABLED,
 IFF(o.SALE_KIND IS NOT NULL,'OVERRIDE',e.INFERRED_REASON) AS CLASSIFICATION_REASON
 FROM inferred e LEFT JOIN EVENT_OVERRIDES o ON o.EVENT_ID=e.EVENT_ID
)
SELECT EVENT_ID,SELLER_ID,EVENT_NAME,EVENT_AT,SALE_KIND,SEASON,
 COALESCE(OVERRIDE_PRODUCT_NAME,
  IFF(SALE_KIND='MEMBER',MEMBER_PRODUCT_PREFIX||SEASON,EVENT_NAME)) AS PRODUCT_NAME,
 COALESCE(OVERRIDE_PACKAGE_NAME,
  IFF(SALE_KIND='MEMBER',TRIM(REGEXP_REPLACE(EVENT_NAME,'(19|20)[0-9]{2}','')),NULL)) AS PACKAGE_NAME,
 OPPOSITION,ROUND_NAME,ENABLED,CLASSIFICATION_REASON
FROM resolved;

CREATE OR REPLACE FUNCTION CLEAN_PHONE(P VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
CASE
 WHEN NULLIF(REGEXP_REPLACE(P,'[^0-9+]',''),'') IS NULL THEN NULL
 WHEN REGEXP_REPLACE(P,'[^0-9+]','') LIKE '+%' THEN REGEXP_REPLACE(P,'[^0-9+]','')
 WHEN REGEXP_REPLACE(P,'[^0-9]','') LIKE '610%'
  THEN '+61'||SUBSTR(REGEXP_REPLACE(P,'[^0-9]',''),4)
 WHEN REGEXP_REPLACE(P,'[^0-9]','') LIKE '0%'
  THEN '+61'||SUBSTR(REGEXP_REPLACE(P,'[^0-9]',''),2)
 ELSE '+'||REGEXP_REPLACE(P,'[^0-9]','') END
$$;

-- 2. Use only the updated source views. Do not read the raw table.
CREATE OR REPLACE VIEW V_CUSTOMERS AS
SELECT CUSTOMER_ID,SELLER_ID,NULLIF(TRIM(EMAIL),'') AS EMAIL,
 NULLIF(TRIM(FIRST_NAME),'') AS FIRST_NAME,NULLIF(TRIM(LAST_NAME),'') AS LAST_NAME,
 PHONE,LOCATION_CITY AS CITY,DOB,GENDER,LEGACY_TICKETEK_CUSTOMER_ID AS LEGACY_CUSTOMER_ID,
 LAST_CHANGED_AT
FROM RAW_INGESTION.VIVENU_NATIVE.CUSTOMERS;

-- Recover one header per transaction; TRANSACTIONS already expands its lines.
CREATE OR REPLACE VIEW V_ORDER_HEADERS AS
SELECT * FROM RAW_INGESTION.VIVENU_NATIVE.TRANSACTIONS
QUALIFY ROW_NUMBER() OVER(PARTITION BY TRANSACTION_ID
 ORDER BY LINE_ITEM_INDEX ASC NULLS LAST)=1;

CREATE OR REPLACE VIEW V_ORDERS AS
SELECT r.TRANSACTION_ID AS ORDER_ID,r.SELLER_ID,r.EVENT_ID,r.CUSTOMER_ID,
 COALESCE(NULLIF(TRIM(r.EMAIL),''),c.EMAIL) AS EMAIL,
 COALESCE(NULLIF(TRIM(r.FIRST_NAME),''),c.FIRST_NAME) AS FIRST_NAME,
 COALESCE(NULLIF(TRIM(r.LAST_NAME),''),c.LAST_NAME) AS LAST_NAME,
 COALESCE(NULLIF(r.PHONE,''),c.PHONE) AS PHONE,
 COALESCE(NULLIF(r.LOCATION_CITY,''),c.CITY) AS CITY,
 UPPER(r.STATUS) AS STATUS,UPPER(r.PAYMENT_STATUS) AS PAYMENT_STATUS,
 r.CURRENCY,r.REAL_PRICE AS ORDER_TOTAL,r.CREATED_AT,
 r.CANCELLATION_ITEM_COUNT AS CANCEL_ITEM_COUNT,r.LINE_ITEMS AS LINES,r.LAST_CHANGED_AT,
 m.SALE_KIND,m.SEASON,m.PRODUCT_NAME,m.PACKAGE_NAME,m.OPPOSITION,m.ROUND_NAME,
 m.EVENT_NAME,m.EVENT_AT,m.CLASSIFICATION_REASON,m.ENABLED AS EVENT_ENABLED
FROM V_ORDER_HEADERS r
LEFT JOIN V_CUSTOMERS c ON c.CUSTOMER_ID=r.CUSTOMER_ID AND c.SELLER_ID=r.SELLER_ID
LEFT JOIN V_EVENT_MAP m ON m.EVENT_ID=r.EVENT_ID AND m.SELLER_ID=r.SELLER_ID;

CREATE OR REPLACE VIEW V_EVENT_CATEGORIES AS
SELECT e.EVENT_ID,e.SELLER_ID,
 c.VALUE:ref::VARCHAR AS CATEGORY_REF,c.VALUE:name::VARCHAR AS CATEGORY_NAME
FROM RAW_INGESTION.VIVENU_NATIVE.EVENTS e,
 LATERAL FLATTEN(INPUT=>e.CATEGORIES) c
QUALIFY ROW_NUMBER() OVER(PARTITION BY e.EVENT_ID,c.VALUE:ref::VARCHAR
 ORDER BY c.INDEX)=1;

CREATE OR REPLACE VIEW V_LINES AS
SELECT o.*,t.LINE_ITEM_INDEX AS LINE_INDEX,t.LINE_ITEM_ID AS LINE_ID,
 t.LINE_ITEM_TICKET_TYPE_ID AS PRODUCT_ID,t.LINE_ITEM_NAME AS LINE_NAME,
 t.LINE_ITEM_PRICE AS UNIT_PRICE,
 TRY_TO_DECIMAL(t.LINE_ITEM_DATA:amount::VARCHAR,18,4) AS QUANTITY,
 t.LINE_ITEM_CATEGORY_REF AS CATEGORY_REF,t.LINE_ITEM_PLAN_ID AS PLAN_ID
FROM V_ORDERS o JOIN RAW_INGESTION.VIVENU_NATIVE.TRANSACTIONS t
 ON t.TRANSACTION_ID=o.ORDER_ID AND t.SELLER_ID=o.SELLER_ID
WHERE t.LINE_ITEM_INDEX IS NOT NULL;

CREATE OR REPLACE VIEW V_TICKETS AS
SELECT TICKET_ID,SELLER_ID,NULLIF(TRANSACTION_ID,'') AS ORDER_ID,
 CART_ITEM_ID AS LINE_ID,EVENT_ID,TICKET_TYPE_ID AS PRODUCT_ID,
 NULLIF(TRIM(EMAIL),'') AS EMAIL,NULLIF(TRIM(FIRST_NAME),'') AS FIRST_NAME,
 NULLIF(TRIM(LAST_NAME),'') AS LAST_NAME,LOCATION_CITY AS CITY,
 CATEGORY_NAME,TICKET_NAME AS TYPE_NAME,UPPER(STATUS) AS STATUS,
 BARCODE,DOB,GENDER,NULLIF(MEMBER_NUMBER,'') AS MEMBER_NUMBER,
 MEMBER_SINCE,LAST_CHANGED_AT,TICKET_TYPE
FROM RAW_INGESTION.VIVENU_NATIVE.TICKETS;

CREATE OR REPLACE VIEW V_CLASSIFICATION_REVIEW AS
WITH multi_events AS (
 SELECT DISTINCT ORDER_ID,SELLER_ID,EVENT_ID FROM V_TICKETS
 WHERE UPPER(TICKET_TYPE)='MULTI'
)
SELECT DISTINCT l.ORDER_ID FROM V_LINES l
LEFT JOIN multi_events m ON m.ORDER_ID=l.ORDER_ID AND m.SELLER_ID=l.SELLER_ID
 AND m.EVENT_ID=l.EVENT_ID
WHERE l.CLASSIFICATION_REASON='DEFAULT_MATCH_RULE'
 AND (NULLIF(l.PLAN_ID,'') IS NOT NULL OR m.ORDER_ID IS NOT NULL);

-- Order-wide checks prevent incomplete or misleading totals.
CREATE OR REPLACE VIEW V_ORDER_CHECKS AS
WITH checks AS (
 SELECT ORDER_ID,
 COUNT_IF(LINE_ID IS NULL OR UNIT_PRICE IS NULL OR UNIT_PRICE<0
  OR QUANTITY IS NULL OR QUANTITY<=0 OR QUANTITY<>FLOOR(QUANTITY) OR PRODUCT_ID IS NULL) AS BAD_LINES,
 COUNT(*)-COUNT(DISTINCT LINE_ID) AS DUPLICATE_LINES
 FROM V_LINES GROUP BY ORDER_ID
)
SELECT o.ORDER_ID,
 CASE
 WHEN o.SALE_KIND IS NULL THEN 'MISSING_EVENT_CLASSIFICATION'
 WHEN NOT o.EVENT_ENABLED THEN 'EVENT_DISABLED'
 WHEN o.SEASON IS NULL THEN 'SEASON_REVIEW'
 WHEN cr.ORDER_ID IS NOT NULL THEN 'MEMBERSHIP_CLASSIFICATION_REVIEW'
 WHEN o.SALE_KIND NOT IN ('MATCH','MEMBER') THEN 'INVALID_EVENT_KIND'
 WHEN o.STATUS IS DISTINCT FROM 'COMPLETE' THEN 'ORDER_NOT_COMPLETE'
 WHEN o.PAYMENT_STATUS IS DISTINCT FROM 'RECEIVED' THEN 'PAYMENT_NOT_RECEIVED'
 WHEN o.CANCEL_ITEM_COUNT>0 THEN 'PARTIAL_CANCELLATION_REVIEW'
 WHEN o.CURRENCY IS DISTINCT FROM 'AUD' THEN 'CURRENCY_REVIEW'
 WHEN o.EMAIL IS NULL THEN 'MISSING_PURCHASER_EMAIL'
 WHEN o.CREATED_AT IS NULL THEN 'MISSING_ORDER_DATE'
 WHEN COALESCE(ARRAY_SIZE(o.LINES),0)=0 THEN 'NO_TICKET_LINES'
 WHEN c.BAD_LINES>0 THEN 'INVALID_LINE'
 WHEN c.DUPLICATE_LINES>0 THEN 'DUPLICATE_LINE_ID'
 ELSE 'READY' END AS RESULT
FROM V_ORDERS o LEFT JOIN checks c ON c.ORDER_ID=o.ORDER_ID
LEFT JOIN V_CLASSIFICATION_REVIEW cr ON cr.ORDER_ID=o.ORDER_ID;

CREATE OR REPLACE VIEW V_MEMBER_LINE_CHECKS AS
SELECT l.ORDER_ID,l.LINE_ID,l.QUANTITY,
 COUNT(t.TICKET_ID) AS VALID_TICKET_COUNT,
 COUNT_IF(t.TICKET_ID IS NOT NULL AND
  (COALESCE(t.FIRST_NAME,l.FIRST_NAME) IS NULL OR
   COALESCE(t.LAST_NAME,l.LAST_NAME) IS NULL OR
   t.MEMBER_NUMBER IS NULL OR t.BARCODE IS NULL)) AS INCOMPLETE_MEMBERS
FROM V_LINES l JOIN V_ORDER_CHECKS q ON q.ORDER_ID=l.ORDER_ID AND q.RESULT='READY'
LEFT JOIN V_TICKETS t ON t.ORDER_ID=l.ORDER_ID AND t.LINE_ID=l.LINE_ID
 AND t.SELLER_ID=l.SELLER_ID AND t.EVENT_ID=l.EVENT_ID
 AND t.PRODUCT_ID=l.PRODUCT_ID AND t.STATUS='VALID'
WHERE l.SALE_KIND='MEMBER'
GROUP BY l.ORDER_ID,l.LINE_ID,l.QUANTITY;

CREATE OR REPLACE VIEW V_ISSUES AS
SELECT ORDER_ID,RESULT AS ISSUE FROM V_ORDER_CHECKS WHERE RESULT<>'READY'
UNION ALL
SELECT DISTINCT ORDER_ID,'MEMBER_TICKET_COUNT_OR_DETAILS'
FROM V_MEMBER_LINE_CHECKS
WHERE VALID_TICKET_COUNT<>QUANTITY OR INCOMPLETE_MEMBERS>0;

CREATE OR REPLACE VIEW V_READY_LINES AS
SELECT l.* FROM V_LINES l
WHERE NOT EXISTS (SELECT 1 FROM V_ISSUES i WHERE i.ORDER_ID=l.ORDER_ID);

CREATE OR REPLACE VIEW V_MEMBERS AS
SELECT l.*, t.TICKET_ID,t.BARCODE,t.MEMBER_NUMBER,t.MEMBER_SINCE,t.DOB,t.GENDER,
 COALESCE(t.EMAIL,l.EMAIL) AS MEMBER_EMAIL,
 COALESCE(t.FIRST_NAME,l.FIRST_NAME) AS MEMBER_FIRST_NAME,
 COALESCE(t.LAST_NAME,l.LAST_NAME) AS MEMBER_LAST_NAME,
 COALESCE(t.CITY,l.CITY) AS MEMBER_CITY,
 t.CATEGORY_NAME,COALESCE(t.TYPE_NAME,l.LINE_NAME) AS TYPE_NAME,
 t.LAST_CHANGED_AT AS TICKET_CHANGED_AT
FROM V_READY_LINES l JOIN V_TICKETS t
 ON t.ORDER_ID=l.ORDER_ID AND t.LINE_ID=l.LINE_ID AND t.SELLER_ID=l.SELLER_ID
 AND t.EVENT_ID=l.EVENT_ID AND t.PRODUCT_ID=l.PRODUCT_ID AND t.STATUS='VALID'
WHERE l.SALE_KIND='MEMBER'
 AND LOWER(COALESCE(t.TYPE_NAME,l.LINE_NAME,'')) NOT LIKE '%complimentary%'
 AND LOWER(COALESCE(t.TYPE_NAME,l.LINE_NAME,'')) NOT LIKE '%stakeholder%';

-- 3. Profile payloads. One deterministic profile per exact trimmed email.
-- Shared-email members: choose oldest known DOB, then newest purchase/ticket.
CREATE OR REPLACE VIEW V_PROFILE_PICKS AS
WITH p AS (
 SELECT 'TICKETEK_NWA_PROFILES' AS TARGET_NAME,EMAIL,FIRST_NAME,LAST_NAME,CITY,PHONE,
  NULL::DATE AS DOB,NULL::VARCHAR AS GENDER,NULL::VARCHAR AS MEMBER_NUMBER,
  NULL::VARCHAR AS MEMBER_SINCE,CREATED_AT,ORDER_ID,'' AS TICKET_ID
 FROM V_READY_LINES WHERE SALE_KIND='MATCH'
 UNION ALL
 SELECT 'TICKETEK_MEMBER_PROFILES',MEMBER_EMAIL,MEMBER_FIRST_NAME,MEMBER_LAST_NAME,
  MEMBER_CITY,PHONE,DOB,GENDER,MEMBER_NUMBER,MEMBER_SINCE,CREATED_AT,ORDER_ID,TICKET_ID
 FROM V_MEMBERS
)
SELECT * FROM p QUALIFY ROW_NUMBER() OVER (
 PARTITION BY TARGET_NAME,EMAIL
 ORDER BY DOB ASC NULLS LAST,CREATED_AT DESC,ORDER_ID DESC,TICKET_ID DESC)=1;

CREATE OR REPLACE VIEW V_PROFILE_SUBSCRIPTIONS AS
SELECT p.TARGET_NAME,p.EMAIL,
 ARRAY_AGG(OBJECT_CONSTRUCT('subscription_group_id',g.GROUP_ID,
  'subscription_state','subscribed')) WITHIN GROUP(ORDER BY g.GROUP_ID) AS GROUPS
FROM V_PROFILE_PICKS p CROSS JOIN CONTROL c
JOIN SUBSCRIPTION_GROUP_CONFIG g ON g.ENVIRONMENT=c.ENVIRONMENT
 AND g.TARGET_NAME=p.TARGET_NAME AND g.ENABLED
 AND (g.MIN_AGE IS NULL OR FLOOR(MONTHS_BETWEEN(CURRENT_DATE(),p.DOB)/12)>=g.MIN_AGE)
WHERE c.CONFIG_ID=1 GROUP BY p.TARGET_NAME,p.EMAIL;

CREATE OR REPLACE VIEW V_PROFILE_CANDIDATES AS
SELECT p.TARGET_NAME,SHA2(TRIM(p.EMAIL),256) AS EXTERNAL_ID,
 OBJECT_CONSTRUCT('country','AU',
 'email',IFF(p.TARGET_NAME='TICKETEK_NWA_PROFILES',LOWER(p.EMAIL),p.EMAIL),
 'first_name',IFF(p.TARGET_NAME='TICKETEK_NWA_PROFILES',INITCAP(p.FIRST_NAME),p.FIRST_NAME),
 'last_name',IFF(p.TARGET_NAME='TICKETEK_NWA_PROFILES',INITCAP(p.LAST_NAME),p.LAST_NAME),
 'home_city',IFF(p.TARGET_NAME='TICKETEK_NWA_PROFILES',INITCAP(p.CITY),p.CITY),
 'phone',CLEAN_PHONE(p.PHONE),'email_subscribe','subscribed',
 'Dob',p.DOB,'Gender',p.GENDER,'member_number',p.MEMBER_NUMBER,'member_since',p.MEMBER_SINCE,
 'subscription_groups',COALESCE(sg.GROUPS,ARRAY_CONSTRUCT())) AS PAYLOAD
FROM V_PROFILE_PICKS p LEFT JOIN V_PROFILE_SUBSCRIPTIONS sg
 ON sg.TARGET_NAME=p.TARGET_NAME AND sg.EMAIL=p.EMAIL;

-- Membership amounts allocated per member ticket, not repeated order totals.
CREATE OR REPLACE VIEW V_MEMBER_PRODUCTS AS
SELECT ORDER_ID,MEMBER_EMAIL AS EMAIL,CREATED_AT,PRODUCT_ID,UNIT_PRICE,
 SEASON,PACKAGE_NAME,CATEGORY_NAME,TYPE_NAME,PRODUCT_NAME,
 COUNT(*) AS QUANTITY,
 ARRAY_AGG(DISTINCT BARCODE) WITHIN GROUP(ORDER BY BARCODE) AS BARCODES
FROM V_MEMBERS
GROUP BY ORDER_ID,MEMBER_EMAIL,CREATED_AT,PRODUCT_ID,UNIT_PRICE,
 SEASON,PACKAGE_NAME,CATEGORY_NAME,TYPE_NAME,PRODUCT_NAME;

CREATE OR REPLACE VIEW V_EVENT_BASE AS
WITH match_products AS (
 SELECT ORDER_ID,EMAIL,FIRST_NAME,LAST_NAME,CREATED_AT,LINE_ID,
 UNIT_PRICE*QUANTITY AS LINE_TOTAL,
 OBJECT_CONSTRUCT('product_id',PRODUCT_ID,'product_name',COALESCE(PRODUCT_NAME,EVENT_NAME),
 'variant_id',CONCAT_WS('-',SEASON,'R'||COALESCE(ROUND_NAME,''),
 COALESCE(ec.CATEGORY_NAME,''),COALESCE(LINE_NAME,'')),
 'quantity',QUANTITY,'price',UNIT_PRICE,
 'metadata',OBJECT_CONSTRUCT('season',SEASON,'opposition',OPPOSITION,'round',ROUND_NAME,
 'price_category',ec.CATEGORY_NAME,'price_type',LINE_NAME,
 'purchase_date',TO_CHAR(CREATED_AT,'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'),
 'event_date',TO_CHAR(EVENT_AT,'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'))) AS PRODUCT
 FROM V_READY_LINES l LEFT JOIN V_EVENT_CATEGORIES ec
 ON ec.EVENT_ID=l.EVENT_ID AND ec.SELLER_ID=l.SELLER_ID
 AND ec.CATEGORY_REF=l.CATEGORY_REF
 WHERE SALE_KIND='MATCH'
), member_identity AS (
 SELECT ORDER_ID,MEMBER_EMAIL AS EMAIL,MEMBER_FIRST_NAME AS FIRST_NAME,
 MEMBER_LAST_NAME AS LAST_NAME,DOB FROM V_MEMBERS
 QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID,MEMBER_EMAIL
 ORDER BY DOB ASC NULLS LAST,TICKET_ID)=1
), member_products AS (
 SELECT p.ORDER_ID,p.EMAIL,i.FIRST_NAME,i.LAST_NAME,i.DOB,p.CREATED_AT,
 p.PRODUCT_ID,p.TYPE_NAME,p.CATEGORY_NAME,p.UNIT_PRICE,
 p.UNIT_PRICE*p.QUANTITY AS LINE_TOTAL,
 OBJECT_CONSTRUCT('product_id',p.PRODUCT_ID,'product_name',p.PRODUCT_NAME,
 'variant_id',CONCAT_WS('-',p.SEASON,COALESCE(p.PACKAGE_NAME,''),
 COALESCE(p.CATEGORY_NAME,''),COALESCE(p.TYPE_NAME,'')),
 'quantity',p.QUANTITY,'price',p.UNIT_PRICE,
 'metadata',OBJECT_CONSTRUCT('season',p.SEASON,'member_package',p.PACKAGE_NAME,
 'member_category',p.CATEGORY_NAME,'member_type',p.TYPE_NAME,
 'purchase_date',TO_CHAR(p.CREATED_AT,'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'),
 'member_barcode',p.BARCODES)) AS PRODUCT
 FROM V_MEMBER_PRODUCTS p JOIN member_identity i
 ON i.ORDER_ID=p.ORDER_ID AND i.EMAIL=p.EMAIL
), orders AS (
 SELECT 'TICKETEK_NWA_SALES' AS TARGET_NAME,'ecommerce.order_placed' AS EVENT_NAME,
 ORDER_ID,EMAIL,FIRST_NAME,LAST_NAME,CREATED_AT,NULL::DATE AS DOB,
 SUM(LINE_TOTAL)::NUMBER(18,2) AS TOTAL_VALUE,
 ARRAY_AGG(PRODUCT) WITHIN GROUP(ORDER BY LINE_ID) AS PRODUCTS
 FROM match_products GROUP BY ORDER_ID,EMAIL,FIRST_NAME,LAST_NAME,CREATED_AT
 UNION ALL
 SELECT 'TICKETEK_MEMBER_SALES','membership.completed',
 ORDER_ID,EMAIL,FIRST_NAME,LAST_NAME,CREATED_AT,DOB,
 SUM(LINE_TOTAL)::NUMBER(18,2),
 ARRAY_AGG(PRODUCT) WITHIN GROUP(ORDER BY PRODUCT_ID,TYPE_NAME,CATEGORY_NAME,UNIT_PRICE)
 FROM member_products GROUP BY ORDER_ID,EMAIL,FIRST_NAME,LAST_NAME,CREATED_AT,DOB
)
SELECT TARGET_NAME,ORDER_ID,EMAIL,DOB,SHA2(TRIM(EMAIL),256) AS EXTERNAL_ID,
 OBJECT_CONSTRUCT('country','AU','email',EMAIL,'first_name',FIRST_NAME,
 'last_name',LAST_NAME,'name',EVENT_NAME,
 'time',TO_CHAR(CREATED_AT,'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM'),
 'properties',OBJECT_CONSTRUCT('order_id','vivenu:'||ORDER_ID,
 'total_value',TOTAL_VALUE,'currency','AUD','source','ticketing_platform','products',PRODUCTS)
 ) AS BASE_PAYLOAD
FROM orders;

CREATE OR REPLACE VIEW V_EVENT_SUBSCRIPTIONS AS
SELECT e.TARGET_NAME,e.ORDER_ID,e.EXTERNAL_ID,
 ARRAY_AGG(OBJECT_CONSTRUCT('subscription_group_id',g.GROUP_ID,
 'subscription_state','subscribed')) WITHIN GROUP(ORDER BY g.GROUP_ID) AS GROUPS
FROM V_EVENT_BASE e CROSS JOIN CONTROL c
JOIN SUBSCRIPTION_GROUP_CONFIG g ON g.ENVIRONMENT=c.ENVIRONMENT
 AND g.TARGET_NAME=e.TARGET_NAME AND g.ENABLED
 AND (g.MIN_AGE IS NULL OR FLOOR(MONTHS_BETWEEN(CURRENT_DATE(),e.DOB)/12)>=g.MIN_AGE)
WHERE c.CONFIG_ID=1 GROUP BY e.TARGET_NAME,e.ORDER_ID,e.EXTERNAL_ID;

CREATE OR REPLACE VIEW V_EVENT_CANDIDATES AS
SELECT e.TARGET_NAME,e.EXTERNAL_ID,
 IFF(e.TARGET_NAME='TICKETEK_MEMBER_SALES' OR sg.GROUPS IS NOT NULL,
 OBJECT_INSERT(e.BASE_PAYLOAD,'subscription_groups',COALESCE(sg.GROUPS,ARRAY_CONSTRUCT())),
 e.BASE_PAYLOAD) AS PAYLOAD
FROM V_EVENT_BASE e LEFT JOIN V_EVENT_SUBSCRIPTIONS sg
 ON sg.TARGET_NAME=e.TARGET_NAME AND sg.ORDER_ID=e.ORDER_ID AND sg.EXTERNAL_ID=e.EXTERNAL_ID;

CREATE OR REPLACE VIEW V_CANDIDATES AS
SELECT * FROM V_PROFILE_CANDIDATES UNION ALL SELECT * FROM V_EVENT_CANDIDATES;

-- 4. Validation outputs and atomic refresh/publication.
CREATE TABLE IF NOT EXISTS TICKETEK_NWA_PROFILES (UPDATED_AT TIMESTAMP_NTZ, EXTERNAL_ID VARCHAR, PAYLOAD VARCHAR);
CREATE TABLE IF NOT EXISTS TICKETEK_NWA_SALES (UPDATED_AT TIMESTAMP_NTZ, EXTERNAL_ID VARCHAR, PAYLOAD VARCHAR);
CREATE TABLE IF NOT EXISTS TICKETEK_MEMBER_PROFILES (UPDATED_AT TIMESTAMP_NTZ, EXTERNAL_ID VARCHAR, PAYLOAD VARCHAR);
CREATE TABLE IF NOT EXISTS TICKETEK_MEMBER_SALES (UPDATED_AT TIMESTAMP_NTZ, EXTERNAL_ID VARCHAR, PAYLOAD VARCHAR);

CREATE OR REPLACE PROCEDURE SP_REFRESH_VIVENU_BRAZE(PUBLISH BOOLEAN)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS CALLER AS
$$
DECLARE
 BAD NUMBER DEFAULT 0;
 CAN_PUBLISH BOOLEAN DEFAULT FALSE;
 REPLAY BOOLEAN DEFAULT FALSE;
 RUN_AT TIMESTAMP_NTZ;
 GUARD EXCEPTION (-20001,'Validation failed. Check mappings, keys, target types and CONTROL.');
BEGIN
 SELECT COUNT(*) INTO :BAD FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.CONTROL WHERE CONFIG_ID=1;
 IF (BAD<>1) THEN RAISE GUARD; END IF;
 SELECT ALLOW_PUBLISH,ALLOW_EVENT_REPLAY INTO :CAN_PUBLISH,:REPLAY
 FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.CONTROL WHERE CONFIG_ID=1;
 IF (PUBLISH AND NOT COALESCE(CAN_PUBLISH,FALSE)) THEN RAISE GUARD; END IF;
 SELECT COUNT(*) INTO :BAD FROM (
 SELECT EVENT_ID FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.EVENT_OVERRIDES GROUP BY EVENT_ID HAVING COUNT(*)>1);
 IF (BAD>0) THEN RAISE GUARD; END IF;
 SELECT COUNT(*) INTO :BAD FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.EVENT_OVERRIDES
 WHERE SALE_KIND IS NOT NULL AND SALE_KIND NOT IN ('MATCH','MEMBER');
 IF (BAD>0) THEN RAISE GUARD; END IF;

 SELECT COUNT(*) INTO :BAD FROM (
 SELECT ENVIRONMENT,TARGET_NAME,GROUP_ID FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.SUBSCRIPTION_GROUP_CONFIG
 GROUP BY ENVIRONMENT,TARGET_NAME,GROUP_ID HAVING COUNT(*)>1);
 IF (BAD>0) THEN RAISE GUARD; END IF;
 SELECT COUNT(*) INTO :BAD FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.SUBSCRIPTION_GROUP_CONFIG
 WHERE ENABLED AND (GROUP_ID IS NULL OR TRIM(GROUP_ID)='' OR MIN_AGE<0
 OR ENVIRONMENT IS NULL OR TARGET_NAME NOT IN
 ('TICKETEK_NWA_PROFILES','TICKETEK_MEMBER_PROFILES','TICKETEK_NWA_SALES','TICKETEK_MEMBER_SALES'));
 IF (BAD>0) THEN RAISE GUARD; END IF;
 SELECT COUNT(*) INTO :BAD FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.CONTROL WHERE CONFIG_ID=1 AND
 (DEFAULT_SALE_KIND IS DISTINCT FROM 'MATCH' OR MEMBER_EVENT_NAME_REGEX IS NULL
 OR ENVIRONMENT IS NULL OR MEMBER_PRODUCT_PREFIX IS NULL);
 IF (BAD>0) THEN RAISE GUARD; END IF;

 -- DDL before transaction. Snapshot candidates for consistent output updates.
 CREATE OR REPLACE TEMPORARY TABLE BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES AS
 SELECT TARGET_NAME,EXTERNAL_ID,PARSE_JSON(TO_JSON(PAYLOAD)) AS PAYLOAD,
 COALESCE(PAYLOAD:properties.order_id::VARCHAR,'') AS ORDER_KEY
 FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.V_CANDIDATES;
 SELECT COUNT(*) INTO :BAD FROM (
 SELECT TARGET_NAME,EXTERNAL_ID,ORDER_KEY FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES
 GROUP BY TARGET_NAME,EXTERNAL_ID,ORDER_KEY HAVING COUNT(*)>1);
 IF (BAD>0) THEN RAISE GUARD; END IF;

 IF (PUBLISH) THEN
  -- Require existing three-column contracts, including UTC TIMESTAMP_NTZ update precision.
  SELECT COUNT(*) INTO :BAD
  FROM BRAZE_CLOUD_PRODUCTION.INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA='INGESTION'
   AND TABLE_NAME IN ('TICKETEK_NWA_PROFILES','TICKETEK_NWA_SALES',
                     'TICKETEK_MEMBER_PROFILES','TICKETEK_MEMBER_SALES')
   AND ((COLUMN_NAME='UPDATED_AT' AND DATA_TYPE='TIMESTAMP_NTZ')
    OR (COLUMN_NAME='EXTERNAL_ID' AND DATA_TYPE IN ('TEXT','VARCHAR'))
    OR (COLUMN_NAME='PAYLOAD' AND DATA_TYPE IN ('TEXT','VARCHAR')));
  IF (BAD<>12) THEN RAISE GUARD; END IF;
  SELECT COUNT(*) INTO :BAD FROM (
   SELECT EXTERNAL_ID FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_NWA_PROFILES
   GROUP BY EXTERNAL_ID HAVING COUNT(*)>1);
  IF (BAD>0) THEN RAISE GUARD; END IF;
  SELECT COUNT(*) INTO :BAD FROM (
   SELECT EXTERNAL_ID,TRY_PARSE_JSON(PAYLOAD):properties.order_id::VARCHAR FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_NWA_SALES
   GROUP BY EXTERNAL_ID,TRY_PARSE_JSON(PAYLOAD):properties.order_id::VARCHAR HAVING COUNT(*)>1);
  IF (BAD>0) THEN RAISE GUARD; END IF;
  SELECT COUNT(*) INTO :BAD FROM (
   SELECT EXTERNAL_ID FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_MEMBER_PROFILES
   GROUP BY EXTERNAL_ID HAVING COUNT(*)>1);
  IF (BAD>0) THEN RAISE GUARD; END IF;
  SELECT COUNT(*) INTO :BAD FROM (
   SELECT EXTERNAL_ID,TRY_PARSE_JSON(PAYLOAD):properties.order_id::VARCHAR FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_MEMBER_SALES
   GROUP BY EXTERNAL_ID,TRY_PARSE_JSON(PAYLOAD):properties.order_id::VARCHAR HAVING COUNT(*)>1);
  IF (BAD>0) THEN RAISE GUARD; END IF;
 END IF;
 RUN_AT := CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
 BEGIN
  BEGIN TRANSACTION;
  MERGE INTO BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.TICKETEK_NWA_PROFILES t USING
   (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_NWA_PROFILES') s
  ON t.EXTERNAL_ID=s.EXTERNAL_ID
  WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
   THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
  WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
   VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
  MERGE INTO BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.TICKETEK_NWA_SALES t USING
   (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_NWA_SALES') s
  ON t.EXTERNAL_ID=s.EXTERNAL_ID AND TRY_PARSE_JSON(t.PAYLOAD):properties.order_id::VARCHAR=s.ORDER_KEY
  WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
   THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
  WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
   VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
  MERGE INTO BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.TICKETEK_MEMBER_PROFILES t USING
   (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_MEMBER_PROFILES') s
  ON t.EXTERNAL_ID=s.EXTERNAL_ID
  WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
   THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
  WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
   VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
  MERGE INTO BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.TICKETEK_MEMBER_SALES t USING
   (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_MEMBER_SALES') s
  ON t.EXTERNAL_ID=s.EXTERNAL_ID AND TRY_PARSE_JSON(t.PAYLOAD):properties.order_id::VARCHAR=s.ORDER_KEY
  WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
   THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
  WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
   VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
  IF (PUBLISH) THEN
   MERGE INTO BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_NWA_PROFILES t USING
    (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_NWA_PROFILES') s
   ON t.EXTERNAL_ID=s.EXTERNAL_ID
   WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
    THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
   WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
    VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
   MERGE INTO BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_NWA_SALES t USING
    (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_NWA_SALES') s
   ON t.EXTERNAL_ID=s.EXTERNAL_ID AND TRY_PARSE_JSON(t.PAYLOAD):properties.order_id::VARCHAR=s.ORDER_KEY
   WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD AND :REPLAY
    THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
   WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
    VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
   MERGE INTO BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_MEMBER_PROFILES t USING
    (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_MEMBER_PROFILES') s
   ON t.EXTERNAL_ID=s.EXTERNAL_ID
   WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD
    THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
   WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
    VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
   MERGE INTO BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_MEMBER_SALES t USING
    (SELECT * FROM BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.RUN_CANDIDATES WHERE TARGET_NAME='TICKETEK_MEMBER_SALES') s
   ON t.EXTERNAL_ID=s.EXTERNAL_ID AND TRY_PARSE_JSON(t.PAYLOAD):properties.order_id::VARCHAR=s.ORDER_KEY
   WHEN MATCHED AND TRY_PARSE_JSON(t.PAYLOAD) IS DISTINCT FROM s.PAYLOAD AND :REPLAY
    THEN UPDATE SET UPDATED_AT=:RUN_AT,PAYLOAD=TO_JSON(s.PAYLOAD)
   WHEN NOT MATCHED THEN INSERT(UPDATED_AT,EXTERNAL_ID,PAYLOAD)
    VALUES(:RUN_AT,s.EXTERNAL_ID,TO_JSON(s.PAYLOAD));
  END IF;
  COMMIT;
 EXCEPTION WHEN OTHER THEN
  ROLLBACK;
  RAISE;
 END;
 RETURN IFF(PUBLISH,'Published eligible rows to existing Braze tables. Review V_ISSUES and event changes.',
 'Validation outputs refreshed. Existing Braze tables unchanged. Review V_ISSUES.');
END;
$$;

-- A single refresh replaces four parallel transformations so shared identities
-- and source mapping are consistent. No scheduled publication until enabled.
CREATE TASK IF NOT EXISTS VIVENU_BRAZE_REFRESH
 WAREHOUSE=WH_BRAZE_PRD
 SCHEDULE='USING CRON 0 6/8 * * * Australia/Perth'
 ALLOW_OVERLAPPING_EXECUTION=FALSE
AS CALL BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.SP_REFRESH_VIVENU_BRAZE(TRUE);

-- Published event changes are held when ALLOW_EVENT_REPLAY=FALSE.
CREATE OR REPLACE VIEW V_PUBLISHED_EVENTS AS
SELECT 'TICKETEK_NWA_SALES' AS TARGET_NAME,EXTERNAL_ID,
 TRY_PARSE_JSON(PAYLOAD) AS PAYLOAD
FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_NWA_SALES
UNION ALL
SELECT 'TICKETEK_MEMBER_SALES',EXTERNAL_ID,TRY_PARSE_JSON(PAYLOAD)
FROM BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_MEMBER_SALES;

CREATE OR REPLACE VIEW V_EVENT_CHANGES_HELD AS
SELECT s.TARGET_NAME,s.EXTERNAL_ID,s.PAYLOAD:properties.order_id::VARCHAR AS ORDER_ID,
 p.PAYLOAD AS PUBLISHED_PAYLOAD,s.PAYLOAD AS CURRENT_PAYLOAD
FROM V_EVENT_CANDIDATES s JOIN V_PUBLISHED_EVENTS p
 ON p.TARGET_NAME=s.TARGET_NAME AND p.EXTERNAL_ID=s.EXTERNAL_ID
 AND p.PAYLOAD:properties.order_id::VARCHAR=s.PAYLOAD:properties.order_id::VARCHAR
WHERE p.PAYLOAD IS DISTINCT FROM PARSE_JSON(TO_JSON(s.PAYLOAD));

CREATE OR REPLACE VIEW V_PUBLISHED_ORDER_ISSUES AS
SELECT p.TARGET_NAME,p.EXTERNAL_ID,i.ORDER_ID,i.ISSUE
FROM V_PUBLISHED_EVENTS p JOIN V_ISSUES i
 ON p.PAYLOAD:properties.order_id::VARCHAR='vivenu:'||i.ORDER_ID;

-- 5. Run the isolated build.
CALL SP_REFRESH_VIVENU_BRAZE(FALSE);

-- 6. Review results before cutover.
SELECT ISSUE,COUNT(*) AS ORDERS FROM V_ISSUES GROUP BY ISSUE ORDER BY ISSUE;
SELECT * FROM V_EVENT_CHANGES_HELD;
SELECT * FROM V_PUBLISHED_ORDER_ISSUES;
SELECT TARGET_NAME,COUNT(*) AS CANDIDATES FROM V_CANDIDATES GROUP BY TARGET_NAME;

-- Inspect automatically derived classifications and season/name choices.
SELECT EVENT_ID,EVENT_NAME,SALE_KIND,SEASON,PRODUCT_NAME,PACKAGE_NAME,
 CLASSIFICATION_REASON,OPPOSITION,ROUND_NAME,ENABLED
FROM V_EVENT_MAP ORDER BY SALE_KIND,EVENT_NAME;

-- Optional override example only. All other fields continue to derive automatically.
-- INSERT INTO EVENT_OVERRIDES (EVENT_ID,SALE_KIND,SEASON,ENABLED)
-- VALUES ('actual-event-id','MEMBER','actual-season',TRUE);

SELECT * FROM SUBSCRIPTION_GROUP_CONFIG ORDER BY ENVIRONMENT,TARGET_NAME,GROUP_ID;

-- Identity case differences can split one person into two legacy email hashes.
SELECT LOWER(PAYLOAD:email::VARCHAR) AS NORMALISED_EMAIL,
 COUNT(DISTINCT EXTERNAL_ID) AS IDENTIFIERS
FROM V_PROFILE_CANDIDATES GROUP BY NORMALISED_EMAIL
HAVING COUNT(DISTINCT EXTERNAL_ID)>1;

-- Missing DOB retains an empty age-gated group array. Review suspicious dates.
SELECT ORDER_ID,TICKET_ID,MEMBER_NUMBER,DOB,MEMBER_SINCE
FROM V_MEMBERS
WHERE DOB IS NULL OR MEMBER_SINCE=TO_CHAR(DOB,'YYYY-MM-DD');

-- Purchaser cannot always be assumed to be a ticket holder/member.
-- Inspect member payloads and their order allocations before publication.
SELECT * FROM TICKETEK_MEMBER_PROFILES LIMIT 20;
SELECT * FROM TICKETEK_MEMBER_SALES LIMIT 20;
SELECT * FROM TICKETEK_NWA_PROFILES LIMIT 20;
SELECT * FROM TICKETEK_NWA_SALES LIMIT 20;

-- Compare line totals with source order totals. Differences may reflect fees,
-- discounts or an unresolved amount meaning. Resolve before enabling publication.
SELECT ORDER_ID,MAX(ORDER_TOTAL) AS API_ORDER_TOTAL,
 SUM(UNIT_PRICE*QUANTITY) AS TICKET_LINE_TOTAL
FROM V_READY_LINES GROUP BY ORDER_ID
HAVING ABS(MAX(ORDER_TOTAL)-SUM(UNIT_PRICE*QUANTITY))>0.01;

/*
7. CUTOVER - run deliberately after validation, not as part of installation.

A. Review V_EVENT_MAP classifications and V_ISSUES. Add EVENT_OVERRIDES only
   for exceptions; adjust the membership name rule if needed. Review the seeded
   SUBSCRIPTION_GROUP_CONFIG settings. Run SP_REFRESH_VIVENU_BRAZE(FALSE) again.
B. Review source status coverage, V_ISSUES, member allocations and price totals.
   If production UPDATED_AT is DATE, review a migration to UTC TIMESTAMP_NTZ with your Braze sync before
   publishing. This script requires TIMESTAMP_NTZ and rejects DATE/TZ/LTZ.
C. Confirm Braze syncs use these four existing ingestion tables. Validate the
   existing membership event subscription_groups behaviour in Braze itself.
D. Stop old refreshes, wait for any current graph run to finish, then publish.
   Preserve a backup and capture Braze sync watermarks before the first publish.

ALTER TASK BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_DATA_LOAD_START SUSPEND;
ALTER TASK IF EXISTS BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE.VIVENU_BRAZE_REFRESH SUSPEND;

UPDATE BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.CONTROL
SET ALLOW_PUBLISH=TRUE WHERE CONFIG_ID=1;

CALL BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.SP_REFRESH_VIVENU_BRAZE(TRUE);

ALTER TASK BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.VIVENU_BRAZE_REFRESH RESUME;

If the V1 Vivenu task was enabled, suspend it too before V2 publication.
Only one publisher should write the existing targets.

The schedule mirrors the old graph, at 06:00, 14:00 and 22:00 Australia/Perth.
Arrange it after successful Vivenu ingestion, or invoke the procedure from the
existing ingestion orchestrator once all required streams succeed. This script
cannot infer that task dependency from the supplied view definitions.

Changed published events are intentionally not updated unless you set
ALLOW_EVENT_REPLAY=TRUE. Keep FALSE until the Braze replay effect is agreed.
Cancellation after an event was sent does not retract that event. This matches
neither a refund workflow nor an unsubscribe instruction; implement those as
separate business changes if needed.

ROLLBACK OF SCHEDULING (does not undo events already ingested by Braze):
ALTER TASK BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.VIVENU_BRAZE_REFRESH SUSPEND;
UPDATE BRAZE_CLOUD_PRODUCTION.VIVENU_BRAZE_V2.CONTROL
SET ALLOW_PUBLISH=FALSE WHERE CONFIG_ID=1;
-- Resume the old root only while the Ticketek share remains usable:
-- ALTER TASK BRAZE_CLOUD_PRODUCTION.INGESTION.TICKETEK_DATA_LOAD_START RESUME;
*/
