{{ config(
    materialized='view',
    alias='EVENTS'
) }}

SELECT
    RECORD_ID AS EVENT_ID,
    DATA:sellerId::VARCHAR AS SELLER_ID,
    DATA:name::VARCHAR AS EVENT_NAME,
    TRY_TO_TIMESTAMP_TZ(DATA:start::VARCHAR) AS START_AT,
    TRY_TO_TIMESTAMP_TZ(DATA:end::VARCHAR) AS END_AT,
    TRY_TO_TIMESTAMP_TZ(DATA:createdAt::VARCHAR) AS CREATED_AT,
    SOURCE_UPDATED_AT AS UPDATED_AT,
    FIRST_LOADED_AT,
    LAST_CHANGED_AT,
    DATA:eventType::VARCHAR AS EVENT_TYPE,
    DATA:timezone::VARCHAR AS EVENT_TIMEZONE,
    DATA:locationName::VARCHAR AS VENUE_NAME,
    DATA:locationCity::VARCHAR AS LOCATION_CITY,
    DATA:locationCountry::VARCHAR AS LOCATION_COUNTRY,
    DATA:categories AS CATEGORIES,
    DATA:tickets AS TICKET_TYPES,
    DATA:tags AS TAGS,
    DATA:groups AS EVENT_GROUPS,
    DATA:childEvents AS CHILD_EVENTS,
    DATA:extraFields AS EVENT_EXTRA_FIELDS,
    DATA:ticketExtraFields AS TICKET_EXTRA_FIELDS,
    DATA:subscriptionSettings AS SUBSCRIPTION_SETTINGS,
    DATA:pricingSettings AS PRICING_SETTINGS,
    TRY_TO_TIMESTAMP_TZ(DATA:sellStart::VARCHAR) AS SELL_START_AT,
    TRY_TO_TIMESTAMP_TZ(DATA:sellEnd::VARCHAR) AS SELL_END_AT,
    SOURCE_CONTEXT AS SOURCE_CONTEXT
FROM {{ source('vivenu_native', 'vivenu_raw_current') }}
WHERE STREAM_NAME = 'events'