{{ config(
    materialized='view',
    alias='SUBSCRIPTIONS'
) }}

SELECT
    RECORD_ID AS SUBSCRIPTION_ID,
    DATA:sellerId::VARCHAR AS SELLER_ID,
    DATA:customerId::VARCHAR AS CUSTOMER_ID,
    DATA:planId::VARCHAR AS PLAN_ID,
    DATA:status::VARCHAR AS STATUS,
    DATA:currency::VARCHAR AS CURRENCY,
    DATA:items AS ITEMS,
    TRY_TO_TIMESTAMP_TZ(DATA:startAt::VARCHAR) AS START_AT,
    TRY_TO_TIMESTAMP_TZ(DATA:canceledAt::VARCHAR) AS CANCELED_AT,
    SOURCE_UPDATED_AT AS UPDATED_AT,
    FIRST_LOADED_AT,
    LAST_CHANGED_AT,
    DATA:email::VARCHAR AS EMAIL,
    DATA:firstname::VARCHAR AS FIRST_NAME,
    DATA:lastname::VARCHAR AS LAST_NAME,
    DATA:name::VARCHAR AS CUSTOMER_NAME,
    DATA:phone::VARCHAR AS PHONE,
    DATA:address AS ADDRESS,
    DATA:consents AS CONSENTS,
    DATA:cycles AS CYCLES,
    DATA:salesChannelId::VARCHAR AS SALES_CHANNEL_ID,
    DATA:origin::VARCHAR AS ORIGIN,
    TRY_TO_TIMESTAMP_TZ(DATA:createdAt::VARCHAR) AS CREATED_AT,
    SOURCE_CONTEXT AS SOURCE_CONTEXT
FROM {{ source('vivenu_native', 'vivenu_raw_current') }}
WHERE STREAM_NAME = 'subscriptions'